"""add_on_delete_for_house

Revision ID: 89960dc37234
Revises: 90ed561e4b22
Create Date: 2023-03-05 19:11:45.208214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89960dc37234'
down_revision = '90ed561e4b22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('house_residential_complex_id_fkey', 'house', type_='foreignkey')
    op.create_foreign_key(None, 'house', 'residential_complexes', ['residential_complex_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'house', type_='foreignkey')
    op.create_foreign_key('house_residential_complex_id_fkey', 'house', 'residential_complexes', ['residential_complex_id'], ['id'])
    # ### end Alembic commands ###
