"""initial

Revision ID: 90ed561e4b22
Revises: 
Create Date: 2023-03-04 17:54:42.578780

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ed561e4b22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    districts = [
        ('zaeltsovsky', 'Заельцовский'),
        ('kalininsky', 'Калининский'),
        ('central', 'Центральный'),
        ('dzerzhinsky', 'Дзержинский'),
        ('october', 'Октябрьский'),
        ('leninsky', 'Ленинский'),
        ('kirovsky', 'Кировский'),
        ('mayday', 'Первомайский'),
        ('soviet', 'Советский'),
        ('railway', 'Железнодорожный'),
    ]

    op.create_table(
        'residential_complexes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('district', sqlalchemy_utils.types.choice.ChoiceType(districts), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'house',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('start_house', sa.Integer(), nullable=False),
        sa.Column('end_house', sa.Integer(), nullable=False),
        sa.Column('link_chat', sa.Text(), nullable=False),
        sa.Column('residential_complex_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['residential_complex_id'],
            ['residential_complexes.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house')
    op.drop_table('residential_complexes')
    # ### end Alembic commands ###
